#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
export EDITOR=emacs
export TERM=xterm-256color
export GOROOT=$HOME/opt/go
export PATH=$GOROOT/bin:$PATH
# Customize to your needs...
